add eks output for key name and workflow steps to check for existing key

diff --git a/.github/workflows/terraform-deploy.yaml b/.github/workflows/terraform-deploy.yaml
--- a/.github/workflows/terraform-deploy.yaml
+++ b/.github/workflows/terraform-deploy.yaml
@@ -40,19 +40,31 @@ jobs:
           role-session-name: GitHubActionsRoleSession
           aws-region: ${{ env.AWS_REGION }}
 
-      # # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-      # - name: Terraform Init
-      #   run: |
-      #     AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
-      #     terraform init -backend-config="bucket=${AWS_ACCOUNT_ID}-state-bucket-${ENVIRONMENT_STAGE}" -backend-config="key=${GITHUB_REF#refs/heads/}.tfstate"
+      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      - name: Terraform Init
+        run: |
+          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
+          terraform init -backend-config="bucket=${AWS_ACCOUNT_ID}-state-bucket-${ENVIRONMENT_STAGE}" -backend-config="key=${GITHUB_REF#refs/heads/}.tfstate"
 
-      # #Checks that all Terraform configuration files adhere to a canonical format
-      # - name: Terraform Format
-      #   run: terraform fmt -check
+      #Checks that all Terraform configuration files adhere to a canonical format
+      - name: Terraform Format
+        run: terraform fmt -check
 
-      # # Generates an execution plan for Terraform
-      # - name: Terraform Plan
-      #   run: terraform plan -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars
+      # Generates an execution plan for Terraform
+      - name: Terraform Plan
+        run: terraform plan -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars
+
+      # Capture Terraform Outputs
+      - name: capture-outputs
+        run: |
+          echo "KEY_NAME=$(terraform output -raw key_pair_name)" >> $GITHUB_ENV
+
+      # Check for existing key pair
+      - name: Check for EC2 key pair
+        id: check-keypair
+        run: |
+          set -e
+          aws ec2 describe-key-pairs --key-name ${KEY_NAME} || echo "Key pair not found"
 
       # # Build infrastructure according to Terraform configuration files
       # - name: Terraform Apply
@@ -69,7 +81,3 @@ jobs:
       #    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/aws/deploy.yaml
       #    kubectl -n ingress-nginx patch service ingress-nginx-controller -p '{"spec":{"externalTrafficPolicy":"Cluster"}}'
       #    echo "$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" 
-
-   
-
-   
